{
 "title": "Fluentd Daemonset",
 "description": "This is a simple dashboard for: https://github.com/banzaicloud/logging-operator utilising Fluent-bit and Fluentd",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "fluentdplugin",
    "label": "Fluentd Plugin",
    "query": {
     "query": "label_values(fluentd_output_status_emit_records, plugin_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "fluentd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fluentd Records by Plugin",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(fluentd_output_status_emit_count{plugin_id=~\"$fluentdplugin\"}[5m]) > 0",
     "legendFormat": "{{ plugin_id }}"
    }
   ]
  },
  {
   "title": "Buffer Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - sum(fluentd_output_status_buffer_available_space_ratio) by (hostname,type)",
     "legendFormat": "{{hostname}} {{type}}"
    }
   ]
  },
  {
   "title": "Fluentd Output Error",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_num_errors{plugin_id=~\"$fluentdplugin\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Fluentd Output Buffer Total Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (fluentd_output_status_buffer_total_bytes{plugin_id=~\"$fluentdplugin\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Fluentd Output Retry",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_retry_count{pod=~\"$pod\",plugin_id=~\"$fluentdplugin\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Fluentd Output Buffer Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (fluentd_output_status_buffer_queue_length{plugin_id=~\"$fluentdplugin\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Retry Rate per min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(hostname, plugin_id)(rate(fluentd_output_status_retry_count[1m])) > 0",
     "legendFormat": "{{plugin_id}}: {{hostname}}"
    }
   ]
  },
  {
   "title": "Writes per min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type)(rate(fluentd_output_status_write_count[1m])) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Output status Emit Records per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (plugin_id)(rate(fluentd_output_status_emit_records[1m])) > 0",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Rollback Rate per min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type, hostname) (rate(fluentd_output_status_rollback_count[1m])) > 0",
     "legendFormat": "{{type}}: {{hostname}}"
    }
   ]
  },
  {
   "title": "Slow Flush Count per min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (plugin_id, type) (rate(fluentd_output_status_slow_flush_count[1m]))",
     "legendFormat": "{{type}}: {{plugin_id}}"
    }
   ]
  },
  {
   "title": "Output status Emit Count per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (plugin_id, type)(rate(fluentd_output_status_emit_count[1m])) >0",
     "legendFormat": "{{type}}: {{plugin_id}}"
    }
   ]
  },
  {
   "title": "Output status Flush time count per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(fluentd_output_status_flush_time_count[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Retry Wait",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (plugin_id)(fluentd_output_status_retry_wait)",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Output status buffer bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type,pluging_id) (fluentd_output_status_buffer_total_bytes)",
     "legendFormat": "{{type}}: {{plugin_id}}"
    }
   ]
  }
 ]
}