- name: "Apache JSON logs processing"
  tags:
    - cfg
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0770
    owner: root
    group: root
  loop:
    - "json2combined.py"


- name: "Mergelog"
  tags:
    - cfg
  unarchive:
    src: https://epi-repository.s3.eu-west-1.amazonaws.com/release/mergelog/mergelog-4.5.tar.gz
    dest: /usr/local
    remote_src: yes


- name: "Scratch/cache directories"
  tags:
    - cfg
    - cron
  file:
    path: "{{ parse.directory }}/{{ item }}"
    owner: root
    group: root
    state: directory
  loop_control:
    label: "{{ item }}"
  loop:
    - daily
    - today



- name: "Log result directories"
  tags:
    - cfg
    - cron
  file:
    path: "{{ parse.dest }}"
    owner: root
    group: root
    state: directory


- name: "Parse script"
  tags:
    - cfg
    - cron
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: root
    group: root
  loop_control:
    label: "{{ item.dest | basename }}"
  loop:
    - { src: "proxy-parse.sh.j2", dest: "{{ parse.file }}" }


- name: "Cron wrapper"
  tags:
    - cfg
    - cron
  template:
    src: "{{ item | basename }}.j2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop_control:
    label: "{{ item | basename }}"
  loop:
    - "{{ parse.wrapper.daily }}"
    - "{{ parse.wrapper.today }}"


- name: "Cron tasks"
  tags:
    - cfg
    - cron
  cron:
    user: root
    day:    "*"
    dow   : "{{ item.dow | default('*') }}"
    name:   "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour:   "{{ item.hour }}"
    job:    "{{ item.job }}"
  loop_control:
    label: "{{ item.name }}"
  loop:
    - { name: "Daily Cache cleanup", minute: "1",  hour: "0", dow: "1", job: "rm -r {{ parse.directory }}/daily/cache" }
    - { name: "Daily Proxy Parse",   minute: "30", hour: "3",           job: "{{ parse.wrapper.daily }}" }
    - { name: "Today Proxy Parse",   minute: "01", hour: "*",           job: "{{ parse.wrapper.today }}" }
