{
 "title": "Fluentd",
 "description": "This is a simple dashboard for: https://github.com/banzaicloud/logging-operator utilising Fluent-bit and Fluentd",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "fluentdplugin",
    "label": "Fluentd Plugin",
    "query": "label_values(fluentd_output_status_emit_records{plugin_id!~\"^object.*\"}, plugin_id)"
   }
  ]
 },
 "panels": [
  { "title": "Aggregated Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fluentd Router Write count / min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_write_count{plugin_id=~\"^out_.*$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Fluentd Router Emit count / min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_emit_count{plugin_id=~\"^out_.*$\"}[1m]))"
    }
   ]
  },
  { "title": "fluentd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Fluentd Records by Plugin",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_emit_count{plugin_id=~\"$fluentdplugin\"}[5m])",
     "legendFormat": "{{ plugin_id }}"
    }
   ]
  },
  {
   "title": "Buffer Usage (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - fluentd_output_status_buffer_available_space_ratio{plugin_id!~\"^object.*\"}",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Fluentd Output Error",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_num_errors{plugin_id=~\"$fluentdplugin\"}[1m])) by (plugin_id)",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Fluentd Output Buffer Total Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_total_bytes{plugin_id=~\"$fluentdplugin\"}",
     "legendFormat": "{{ plugin_id }}"
    }
   ]
  },
  {
   "title": "Fluentd Output Retry",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_retry_count{plugin_id=~\"$fluentdplugin\"}[1m])) by (plugin_id)",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Fluentd Output Buffer Queue Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_queue_length{plugin_id=~\"$fluentdplugin\"}",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Retry Rate per min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_retry_count{plugin_id!~\"^object.*\"}[1m])",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Writes per min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_write_count{plugin_id!~\"^object.*\"}[1m])",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Output status Emit Records per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_emit_records{plugin_id!~\"^object.*\"}[1m])",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Rollback Rate per min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_rollback_count{plugin_id!~\"^object.*\"}[1m])",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Slow Flush Count per min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_slow_flush_count{plugin_id!~\"^object.*\"}[1m])",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Output status Emit Count per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  rate(fluentd_output_status_emit_count{plugin_id!~\"^object.*\"}[1m])",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Output status Flush time count per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_flush_time_count{plugin_id!~\"^object.*\"}[1m])",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Retry Wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_retry_wait{plugin_id!~\"^object.*\"}[1m])",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Output status buffer bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " rate(fluentd_output_status_buffer_total_bytes{plugin_id!~\"^object.*\"}[1m])",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  }
 ]
}