{
 "title": "Alertmanager SNS forwarder",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP 2xx [rpm]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status=~\"2..\"}[1m])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 3xx [rpm]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status=~\"3..\"}[1m])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 4xx [rpm]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status=~\"4..\"}[1m])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx [rpm]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status=~\"5..\"}[1m])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}