---
- name: "VPC: {{ vpc.name }} ({{ vpc.cidr }})"
  tags:
    - asg
    - dns
    - ec2
    - elb
    - net
    - security
  ec2_vpc_net:
    region: "{{ region }}"
    name: "{{ vpc.name }}"
    cidr_block: "{{ vpc.cidr }}"
    purge_tags: false
    tags:
      Ansible: "true"
      Inst: "{{ instance }}"
  register: vpc_net
  when:
    - vpc is defined
    - vpc.name is defined
    - vpc.cidr is defined


- name: "VPC ID ({{ vpc_net.vpc.id }})"
  check_mode: no
  tags:
    - asg
    - dns
    - ec2
    - elb
    - net
    - security
  set_fact:
    vpc_id: "{{ vpc_net.vpc.id }}"
  when:
    - vpc_net is defined
    - vpc_net.vpc is defined
    - vpc_net.vpc.id is defined
