{
 "title": "InfluxDB",
 "description": "The commonly monitored metrics from the built-in `_internal` database of InfluxDB OSS.",
 "tags": [ "influxdb" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "InfluxDB Metric Database", "query": "influxdb" },
   {
    "name": "hostname",
    "query": "show tag values with key=\"hostname\""
   },
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests / Minute",
   "type": "graph",
   "description": "Displays the number of HTTP requests per minute.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Query: $tag_hostname",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(mean(\"queryReq\"), 1m) FROM \"monitor\".\"httpd\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "queryReq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Write: $tag_hostname",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "select": [
      [
       { "params": [ "writeReq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Server Errors: $tag_hostname",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "select": [
      [
       { "params": [ "serverError" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Client Errors: $tag_hostname",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "select": [
      [
       { "params": [ "clientError" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Request Duration (99th %)",
   "type": "graph",
   "description": "Displays the duration, in nanoseconds, of the top 1% of HTTP requests.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Write Request: $tag_hostname",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(percentile(\"writeReqDurationNs\", 99)) / non_negative_derivative(max(\"writeReq\")) AS \"Write Request\"\nFROM \"monitor\".\"httpd\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "writeReqDurationNs" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "Query Request: $tag_hostname",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(percentile(\"queryReqDurationNs\", 99)) / non_negative_derivative(max(\"queryReq\")) AS \"Query Request\"\nFROM \"monitor\".\"httpd\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "writeReqDurationNs" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Continuous Queries Executed / Minute",
   "type": "graph",
   "description": "Displays the non-negative mean rate of change in continuous queries (CQs) executed per minute.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Query OK",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cq",
     "select": [
      [
       { "params": [ "queryOk" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Query Fail",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cq",
     "select": [
      [
       { "params": [ "queryFail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "description": "Displays the current heap size.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "host: $tag_hostname",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "HeapInUse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Shard Write Errors",
   "type": "graph",
   "description": "Displays the number of shard write errors.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "host: $tag_hostname",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "write",
     "select": [
      [
       { "params": [ "writeError" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Point Throughput / Minute by Hostname",
   "type": "graph",
   "description": "Displays the number of points requested each minute, by hostname.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "host: $tag_hostname",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "write",
     "select": [
      [
       { "params": [ "pointReq" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests / Minute",
   "type": "graph",
   "description": "Displays the number of HTTP requests per minute.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "host: $tag_hostname",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queryExecutor",
     "select": [
      [
       { "params": [ "queriesExecuted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Queries Executed / Minute",
   "type": "graph",
   "description": "Displays the number of queries executed per minute.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "host: $tag_hostname",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queryExecutor",
     "select": [
      [
       { "params": [ "queriesExecuted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Series Cardinality by Database",
   "type": "graph",
   "description": "Displays the number of series (series cardinality) for the specified databases.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "database: $tag_database",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "numSeries" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Measurements by Database",
   "type": "graph",
   "description": "Displays the number of measurements, by database.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "database: $tag_database",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "numMeasurements" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Points",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Write Fail",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "pointsWrittenFail" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Write OK",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "pointsWrittenOK" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Series",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of Series",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "numSeries" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Queries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "queryReq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Client Errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "clientError" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Server Errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "serverError" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  }
 ]
}