---
- name: "Proxy config directory"
  tags:
    - cfg
  file:
    state: "directory"
    path : "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: root
    mode: "{{ item.mode | default('0755') }}"
  loop: 
    - { path: "{{ proxy.directory }}" }
    - { path: "{{ proxy.directory }}/cache", mode: "0777" }
    - { path: "{{ proxy.directory }}/ssl" }
    - { path: "{{ proxy.directory }}/vhosts" }
    - { path: "{{ proxy.directory }}/vhosts/extra" }
    - { path: "{{ proxy.directory }}/vhosts/secure" }
    - { path: "{{ proxy.directory }}/{{ vhosts_cfg_dir }}" }


- name: "Install python-passlib"
  tags:
    - pkg
    - pip
  pip:
    name: passlib
    state: latest
  when:
  - proxy.secure is defined
  - secure_proxy is defined
  - secure_proxy[type] is defined
  - not ansible_check_mode


- name: "Proxy config"
  tags:
    - cfg
  template:
    dest: "{{ proxy.directory }}/vhosts/{{ item.dest }}"
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - { src: "apache/block.conf.j2",      dest: "extra/block.conf" }
    - { src: "apache/localhost.conf.j2",  dest: "extra/localhost.conf" }
    - { src: "apache/log-format.conf.j2", dest: "extra/log-format.conf" }
    - { src: "apache/cache.conf.j2",      dest: "extra/cache.conf" }
    - { src: "apache/{{ proxy.config }}", dest: "vhost.conf" }
  loop_control:
    label: '{{ item.dest }}'
  notify: "Reload proxy container"


- name: "Secure access"
  htpasswd:
    path: "{{ proxy.directory }}/vhosts/secure/htpasswd"
    name: "{{ proxy_secure.username }}"
    password: "{{ proxy_secure.password }}"
    owner: root
    group: root
    mode: 0640
  when:
  - proxy.secure is defined
  - secure_proxy is defined
  - secure_proxy[type] is defined


- name: "QoS"
  include_tasks: "qos.yml"


- name: "{{ domain }} ssl"
  tags:
    - cfg
    - ssl
  copy:
    dest: '{{ item.path }}'
    content: '{{ item.content }}'
    owner: root
    group: root
    mode: "0644"
  loop:
    - { path: "{{ proxy.directory }}/ssl/server.crt", content: '{{ ssl.cert }}' }
    - { path: "{{ proxy.directory }}/ssl/server.key", content: '{{ ssl.key }}' }
    - { path: "{{ proxy.directory }}/ssl/server-ca.crt", content: '{{ ssl.ca }}' }
  loop_control:
    label: '{{ item.path }}'
  notify: "Reload proxy container"


- name: "Proxy container"
  tags:
    - container
  docker_container:
    name: "{{ proxy_container.name }}"
    image: "{{ proxy.image }}"
    restart_policy: unless-stopped
    log_driver: "{{ docker.logging.driver }}"
    log_options: "{{ docker.logging.options }}"
    network_mode: "{{ docker.network.mode }}"
    networks:
      - name: "{{ docker.network.name }}"
    networks_cli_compatible: yes
    ports:
      - "{{ proxy_container.port.http }}:{{ proxy.port.http }}"
      - "{{ proxy_container.port.https }}:{{ proxy.port.https }}"
    volumes:
      - "{{ proxy.directory }}/vhosts:/vhosts:rw"
      - "{{ proxy.directory }}/ssl:/certs:rw"
      - "{{ proxy.directory }}/www:/app:rw"
      - "{{ proxy.directory }}/cache:{{ proxy_cache.directory }}:rw"


- name: "Proxy ping file"
  tags:
    - proxy
  copy:
    content: ""
    dest : "{{ proxy.directory }}/www/ping"
    owner: "root"
    group: "root"
    mode: "0644"


- name: Proxy cache clean
  cron:
    name: "Proxy cache clean {{ item.title }}"
    minute: "{{ item.time }}"
    job: "docker exec proxy htcacheclean -tp {{ proxy_cache.directory }} {{ item.options }} 2>&1 | logger -t htcacheclean"
  loop:
    - { title: "size",  time: "30", options: "-l{{ proxy_cache.size }}" }
    - { title: "inode", time: "00", options: "-L{{ proxy_cache.inode }}" }
  loop_control:
    label: '{{ item.title }}'
  when:
  - proxy_cache is defined


- name: "Telegraf"
  include_tasks: "telegraf.yml"


- name: "Services"
  include_tasks: "services.yml"
