- name: "Apache QoS config"
  tags:
    - cfg
  template:
    dest: "{{ proxy.directory }}/vhosts/{{ item.dest }}"
    src: "apache/{{ item.src }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - { src: "global-qos.conf.j2", dest: "global-qos.conf" }
    - { src: "qos.conf.j2",        dest: "extra/qos.conf" }
  loop_control:
    label: '{{ item.dest }}'
  notify: "Reload proxy container"

- name: "Apache Error page directory"
  tags:
    - proxy
  file:
    state: "directory"
    path : "{{ proxy.directory }}/www/{{ proxy.error_page_dir }}"
    owner: "root"
    group: "root"
    mode: "0755"
  notify: "Reload proxy container"
  
- name: "Apache Error pages"
  tags:
    - proxy
  copy:
    src: "{{ item }}"
    dest: "{{ proxy.directory }}/www/{{ proxy.error_page_dir }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop_control:
    label: "{{ item }}"
  loop: "{{ error_pages }}"
  when: error_pages  is defined
  notify: "Reload proxy container"
