- meta: flush_handlers

- name: "Apache container running"
  tags:
    - container
  docker_container:
    name: "{{ proxy_container.name }}"
    state: started
  when: not nginx_enabled


- name: "Nginx container running"
  tags:
    - container
  docker_container:
    name: "{{ nginx_container.name }}"
    state: started
  when: nginx_enabled


- name: "Telegraf service"
  tags:
    - services
  service:
    name:  "telegraf"
    state: started
    enabled: yes
  when: telegraf is defined
