---
- name: "Restart journald"
  service:
    name:  "systemd-journald"
    state: restarted


- name: "Restart NTP"
  service:
    name:  "{{ ntp.service }}"
    state: restarted


- name: "Restart logrotate"
  service:
    name:  "logrotate"
    state: restarted


- name: "Restart rsyslog"
  service:
    name:  "rsyslog"
    state: restarted


- name: "Restart sshd"
  service:
    name:  "{{ (ansible_distribution == 'Ubuntu') | ternary('ssh', 'sshd') }}"
    state: restarted


- name: "Sysctl reload"
  command: "sysctl -p"
