---
- name: "Restart journald"
  service:
    name:  "systemd-journald"
    state: restarted


- name: "Restart NTP"
  service:
    name:  "{{ ntp.service }}"
    state: restarted


- name: "Restart logrotate"
  service:
    name:  "logrotate"
    state: restarted


- name: "Restart rsyslog"
  service:
    name:  "rsyslog"
    state: restarted


- name: "Restart sshd"
  service:
    name:  "{{ (ansible_distribution == 'Ubuntu') | ternary('ssh', 'sshd') }}"
    state: restarted


- name: "Sysctl reload"
  command: "sysctl -p"


- name: "REBOOT"
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: hostname
