- name: "Remove goaccess (if present)"
  tags:
    - goaccess
    - pkg
  package:
    name: goaccess
    state: absent


- name: "Goaccess requirements"
  tags:
    - goaccess
    - pkg
  package:
    name: libmaxminddb
    state: present
