---
- name: "{{ ansible_distribution }}"
  include_tasks: "{{ ansible_distribution }}.yml"


- name: "Goaccess archive [{{ goaccess.url }}]"
  tags:
    - goaccess
  unarchive:
    src: "{{ goaccess.url }}"
    dest: /usr/local
    remote_src: yes


- name: "GeoLite2"
  vars:
    location: "/usr/local/share"
  include_tasks: "geolite2.yml"


- name: "Access DNS"
  tags:
    - dns
  include_role:
    name: dns
