---
- name: "{{ ansible_distribution }}"
  include_tasks: "{{ ansible_distribution }}.yml"


- name: "GeoLite2"
  vars:
  - location: "/usr/local/share"
  include_tasks: "geolite2.yml"


- name: "Access DNS"
  tags:
    - dns
  include_role:
    name: dns
