---
- name: "Remove goaccess (if present)"
  tags:
    - goaccess
    - pkg
  package:
    name: goaccess
    state: absent


- name: "Goaccess requirements"
  tags:
    - goaccess
    - pkg
  package:
#   name: libmaxminddb
    name: http://mirror.centos.org/centos/7/os/x86_64/Packages/libmaxminddb-1.2.0-6.el7.x86_64.rpm
    state: latest


- name: "Goaccess archive"
  tags:
    - goaccess
  unarchive:
    src: https://epi-repository.s3.eu-west-1.amazonaws.com/release/goaccess/goaccess-1.5.2.tgz
    dest: /usr/local
    remote_src: yes


- name: "GeoLite2 archive"
  tags:
    - geoip
  unarchive:
    src: https://epi-repository.s3.eu-west-1.amazonaws.com/release/GeoLite2/GeoLite2-City_20211019.tar.gz
    dest: /usr/local/share
    remote_src: yes


- name: "GeoLite2 DB"
  tags:
    - geoip
    - goaccess
  file:
    src:  ./GeoLite2-City_20211019
    path: /usr/local/share/GeoLite2
    state: link


- name: "Access DNS"
  tags:
    - dns
  include_role:
    name: dns
