---
- name: "Restart docker"
  systemd:
    name:  "{{ docker.service.name | default('docker') }}"
    state: restarted
    daemon_reload: yes

- name: "Restart telegraf"
  systemd:
    name:  "telegraf"
    state: restarted
  when: telegraf is defined


- name: "REBOOT"
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: hostname
  when: docker_group.changed
