bashrc: "{{ (ansible_os_family == 'Debian')  | ternary('/etc/bash.bashrc', '/etc/bashrc') }}"

system_locale: "en_GB.utf8"

ntp:
  absent: "ntp"
  config:
    src: "chrony.conf.j2"
    dest: "{{ (ansible_os_family == 'Debian')  | ternary('/etc/chrony/chrony.conf', '/etc/chrony.conf') }}"
  pkg: "chrony"
  service: "chronyd"
  servers:
    - "169.254.169.123"

