tag: "1.5.0"

proxy:
  directory: "/var/lib/docker/proxy"
  config: "{{ proxy_template }}"
  image:   "{{ registry.common }}/httpd-proxy-oauth/stable:{{ tag }}"
  internal: " /opt/bitnami/apache2/conf"
  port:
    http: 8080
    https: 8443
  secure: "{{ vault_proxy_secure | default(omit) }}"

vhosts_cfg_dir: vhosts/conf.d
