tag: "{{ (nginx_enabled) | ternary(nginx_tag, apache_tag) }}"

apache_tag: "1.5.1"

proxy:
  directory: "/var/lib/docker/proxy"
  config: "{{ proxy_template }}"
  error_page_dir:    error
  image:   "{{ registry.common }}/httpd-proxy-oauth/stable:{{ tag }}"
  internal: " /opt/bitnami/apache2/conf"
  port:
    http: 8080
    https: 8443
  secure: "{{ proxy_secure | default(omit) }}"
  www_user: 1001

proxy_cache:
  size: "1G"
  inode: "250K"
  directory: "/var/cache/apache2/mod_cache_disk"

vhosts_cfg_dir: vhosts/conf.d


nginx_tag: 1.27

nginx:
  directory: "{{ docker.directory }}/{{ nginx_container.name }}"
  image: "{{ registry.common }}/nginx:{{ tag }}"
  buffer: "{{ nginx_buffer }}"
  cache:
    dir: "/var/cache/nginx"
    key: "$scheme$proxy_host$uri$is_args$args$http_origin$http_accept"
    options: "levels=1:2 keys_zone=default:10m max_size=10g inactive=60m use_temp_path=off"
  config: "/etc/nginx"
  port:
    http: 80
    https: 443

nginx_custom_configs: []
nginx_configs:
  - 00-geo2ip.conf
  - 05-log-format.conf
  - 10-blocked.conf
  - 20-qos.conf
  - 30-buffers.conf
  - 40-cache.conf
  - 80-localhost.conf
  - 81-http.conf
  - 82-https.conf

uptime_robot:
  agent: "UptimeRobot"
  hosts:
  - 146.185.143.14/32
  - 167.99.209.234/32
  - 46.101.250.135/32
  - 159.89.8.111/32
  - 139.59.173.249/32
  - 178.62.52.237/32
  - 49.13.24.81/32
  - 49.13.130.29/32
  - 49.13.134.145/32
  - 78.47.98.55/32
  - 88.99.80.227/32
  - 142.132.180.39/32
  - 157.90.155.240/32
  - 157.90.156.63/32
  - 168.119.53.160/32
  - 168.119.96.239/32
  - 49.13.164.148/32
  - 49.13.167.123/32
  - 78.46.190.63/32
  - 78.46.215.1/32
  - 78.47.173.76/32
  - 128.140.41.193/32
  - 128.140.106.114/32
  - 159.69.158.189/32
  - 168.119.123.75/32
  - 167.235.143.113/32
  - 37.27.28.153/32
  - 37.27.29.68/32
  - 37.27.30.213/32
  - 37.27.34.49/32
  - 37.27.82.220/32
  - 37.27.87.149/32
  - 65.109.8.202/32
  - 65.109.129.165/32
  - 65.109.142.78/32
  - 135.181.154.9/32
