tag: "1.5.0"

proxy:
  directory: "/var/lib/docker/proxy"
  config: "{{ proxy_template }}"
  image:   "{{ registry.common }}/httpd-proxy-oauth/stable:{{ tag }}"
  internal: " /opt/bitnami/apache2/conf"
  port:
    http: 8080
    https: 8443
  secure: "{{ proxy_secure | default(omit) }}"

proxy_cache:
  size: "1G"
  inode: "250K"
  directory: "/var/cache/apache2/mod_cache_disk"

vhosts_cfg_dir: vhosts/conf.d
