- name: "Python 3.8 access"
  tags:
    - epel
    - pkg
    - repo
  amzn2extra:
    name: python3.8
    state: present


- name: "Install python3.8"
  become: yes
  tags:
    - pkg
  package:
    name: python3.8
    state: latest

- name: Record interpreter version
  interpreter: {}
  register: interpreter


- name: Python interpreter check
  fail:
    msg: "Ansible is running with the wrong version of Python ({{ interpreter.version }}). Delete the cache (.cache/<hostanme>) and re-run."
  when: interpreter.version is not regex('^3\.8\.')


- name: "Install python3 pin urllib3"
  become: yes
  tags:
    - pkg
    - pip
  pip:
    executable: pip3.8
    name:
      - urllib3<2

- name: "Install python3 pip modules"
  become: yes
  tags:
    - pkg
    - pip
  pip:
    name:
    - 'boto3'
    - 'pytz'
    - 'requests'
    - 'simplejson'
    executable: pip3.8
    state: latest
