---
- name: "Remove goaccess (if present)"
  tags:
    - goaccess
    - pkg
  package:
    name: goaccess
    state: absent


- name: "Goaccess requirements"
  tags:
    - goaccess
    - pkg
  package:
    name: libmaxminddb
    state: latest


- name: "Goaccess archive"
  tags:
    - goaccess
  unarchive:
    src: https://epi-repository.s3.eu-west-1.amazonaws.com/release/goaccess/goaccess-1.5.2.tgz
    dest: /usr/local
    remote_src: yes


- name: "GeoLite2 archive"
  tags:
    - geoip
  unarchive:
    src: https://epi-repository.s3.eu-west-1.amazonaws.com/release/GeoLite2/GeoLite2-City_20211019.tar.gz
    dest: /usr/local/share
    remote_src: yes


- name: "GeoLite2 DB"
  tags:
    - geoip
  file:
    src:  ./GeoLite2-City_20211019
    path: /usr/local/share/GeoLite2
    state: link


- name: "Apache logs processing"
  tags:
    - cfg
    - goaccess
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0770
    owner: root
    group: root
  loop:
    - "json2combined.py"


- name: "Access DNS"
  tags:
    - dns
  include_role:
    name: dns
