---
# Use -e env=real to enable different environments
#
- name: "Environment specific definitions ({{ env }})"
  tags:
    - asg
    - debug
    - dns
    - ec2
    - elb
    - net
    - security
    - vpc
  include_vars: "{{ env }}.yml"


# Key File
- name: "Key File ({{ key.name }})"
  tags:
    - ec2
    - key
  ec2_key:
    region: "{{ region }}"
    name: "{{ key.name }}"
    key_material: "{{ key.material }}"
    purge_tags: false


- name: "IAM"
  include_tasks: "iam.yml"
- name: "Network"
  include_tasks: "network.yml"
- name: "EC2"
  include_tasks: "ec2.yml"


- block:
  - name: "SNS"
    include_tasks: "sns.yml" 
  when: env == "infra"

- name: "Finalise"
  include_tasks: "finalise.yml"
