{
 "title": "Apache",
 "tags": [
  "Influxdb2",
  "Telegraf",
  "Apache"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n    bucket: \"telegraf\",\r\n    measurement: \"apache\",\r\n    tag: \"host\",\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Apache Scoreboard (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apache\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /${host}/)\r\n  |> filter(fn: (r) => r._field == \"scboard_closing\" or r._field == \"scboard_dnslookup\" or r._field == \"scboard_finishing\" or r._field == \"scboard_idle_cleanup\" or r._field == \"scboard_keepalive\" or r._field == \"scboard_logging\" or r._field == \"scboard_reading\" or r._field == \"scboard_sending\" or r._field == \"scboard_starting\" or r._field == \"scboard_waiting\")\r\n"
    }
   ]
  },
  {
   "title": "Apache Workers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apache\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /${host}/)\r\n  |> filter(fn: (r) => r._field == \"BusyWorkers\" or r._field == \"IdleWorkers\")\r\n"
    }
   ]
  },
  {
   "title": "Shared Object Memory Cache",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apache\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /${host}/)\r\n  |> filter(fn: (r) => r._field =~ /^Cache/)\r\n  |> filter(fn: (r) => r._field =~ /Count$/)\r\n"
    }
   ]
  },
  {
   "title": "Apache Cache Timing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apache\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /${host}/)\r\n  |> filter(fn: (r) => r._field =~ /^Cache/)\r\n  |> filter(fn: (r) => r._field =~ /Time/)\r\n"
    }
   ]
  },
  {
   "title": "Shared Object Memory Cache Entries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apache\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /${host}/)\r\n  |> filter(fn: (r) => r._field == \"CacheCurrentEntries\")\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Requests per second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache",
     "query": "from(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apache\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ReqPerSec\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /${host}/)",
     "select": [
      [
       { "params": [ "ReqPerSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}