{
 "title": "Elasticsearch Metrics",
 "tags": [
  "Elasticsearch",
  "Influxdb2",
  "Telegraf"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_nodes",
     "metrics": [
      {
       "field": "source_node.name",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"elasticsearch_cluster_health\")\n  |> filter(fn: (r) => r._field == \"status\")",
     "select": [
      [
       { "params": [ "count_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_nodes",
     "metrics": [
      {
       "field": "source_node.name",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "// SELECT last(\"count_total\") FROM \"elasticsearch_clusterstats_nodes\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_clusterstats_nodes\")\r\n  |> filter(fn: (r) => r._field == \"count_total\")\r\n  |> group()\r\n  |> last()",
     "select": [
      [
       { "params": [ "count_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Active Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "query": "// SELECT last(\"active_shards\") FROM \"$policy\".\"elasticsearch_cluster_health\" WHERE (\"name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_cluster_health\")\r\n  |> filter(fn: (r) => r._field == \"active_shards\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "active_shards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "query": "// SELECT last(\"unassigned_shards\") FROM \"$policy\".\"elasticsearch_cluster_health\" WHERE (\"name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_cluster_health\")\r\n  |> filter(fn: (r) => r._field == \"unassigned_shards\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "unassigned_shards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Docs Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "// SELECT mean(\"docs_count\") FROM \"$policy\".\"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_indices\")\r\n  |> filter(fn: (r) => r._field == \"docs_count\")\r\n  |> group()\r\n  |> last()",
     "select": [
      [
       { "params": [ "docs_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Stored data size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_indices",
     "query": "// SELECT mean(\"store_size_in_bytes\") FROM \"$policy\".\"elasticsearch_clusterstats_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_clusterstats_indices\")\r\n  |> filter(fn: (r) => r._field == \"store_size_in_bytes\")\r\n  |> group()\r\n  |> last()",
     "select": [
      [
       { "params": [ "store_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Used Memory Heap %",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Used Memory Heap %",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "// SELECT mean(\"mem_heap_used_percent\") FROM \"elasticsearch_jvm\" WHERE $timeFilter GROUP BY time(10s) fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_jvm\")\r\n  |> filter(fn: (r) => r._field == \"mem_heap_used_percent\")\r\n  |> group()\r\n  |> last()",
     "select": [
      [
       { "params": [ "mem_heap_used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Health Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "Health Timeline",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"elasticsearch_cluster_health\")\r\n  |> filter(fn: (r) => r._field == \"status\")",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Shards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Primary",
     "bucketAggs": [
      {
       "fake": true,
       "field": "source_node.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_cluster_health",
     "metrics": [
      {
       "field": "node_stats.fs.io_stats.total.operations",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "// SELECT mean(\"active_primary_shards\") FROM \"$policy\".\"elasticsearch_cluster_health\" WHERE (\"name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(linear)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_cluster_health\")\r\n  |> filter(fn: (r) => r._field == \"active_primary_shards\" or  r._field == \"active_shards\" or r._field == \"initializing_shards\" or r._field == \"relocating_shards\" or r._field == \"unassigned_shards\")",
     "select": [
      [
       { "params": [ "active_primary_shards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$cluster$/" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_process",
     "query": "// SELECT mean(\"open_file_descriptors\") FROM \"$policy\".\"elasticsearch_process\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_process\")\r\n  |> filter(fn: (r) => r._field == \"open_file_descriptors\")",
     "select": [
      [
       { "params": [ "open_file_descriptors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Stored Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_indices",
     "query": "// SELECT max(\"store_size_in_bytes\") FROM \"$policy\".\"elasticsearch_clusterstats_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(linear)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_clusterstats_indices\")\r\n  |> filter(fn: (r) => r._field == \"store_size_in_bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)",
     "select": [
      [
       { "params": [ "store_size_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Segments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "// SELECT mean(\"segments_count\") FROM \"$policy\".\"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(linear)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_indices\")\r\n  |> filter(fn: (r) => r._field == \"segments_count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "segments_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "docs values memory",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "//SELECT mean(\"segments_doc_values_memory_in_bytes\") FROM \"elasticsearch_indices\" WHERE $timeFilter GROUP BY time(10s) fill(null)\n\nfrom(bucket: \"telegraf\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_indices\")\n  |> filter(fn: (r) => r._field =~ /^segments_/ and r._field =~ /_bytes$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       {
        "params": [
         "segments_doc_values_memory_in_bytes"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_thread_pool",
     "query": "// SELECT max(\"analyze_queue\") AS \"Analyze\", max(\"ccr_queue\") AS \"CCR\", max(\"fetch_shard_started_queue\") AS \"FetchShard\", max(\"fetch_shard_store_queue\") AS \"FetchShardStore\", max(\"flush_queue\") AS \"Flush\", max(\"force_merge_queue\") AS \"ForceMerge\", max(\"generic_queue\") AS \"Generic\", max(\"get_queue\") AS \"Get\", max(\"index_queue\") AS \"Index\", max(\"listener_queue\") AS \"Listener\", max(\"management_queue\") AS \"Management\", max(\"rollup_indexing_queue\") AS \"RollUPIndexing\", max(\"search_queue\") AS \"Search\", max(\"write_queue\") AS \"Write\" FROM \"$policy\".\"elasticsearch_thread_pool\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(previous)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_thread_pool\")\r\n  |> filter(fn: (r) => r._field =~ /_queue/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "analyze_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Analyze" ], "type": "alias" }
      ],
      [
       { "params": [ "ccr_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "CCR" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_started_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "FetchShard" ], "type": "alias" }
      ],
      [
       { "params": [ "fetch_shard_store_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "FetchShardStore" ], "type": "alias" }
      ],
      [
       { "params": [ "flush_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Flush" ], "type": "alias" }
      ],
      [
       { "params": [ "force_merge_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "ForceMerge" ], "type": "alias" }
      ],
      [
       { "params": [ "generic_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Generic" ], "type": "alias" }
      ],
      [
       { "params": [ "get_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Get" ], "type": "alias" }
      ],
      [
       { "params": [ "index_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Index" ], "type": "alias" }
      ],
      [
       { "params": [ "listener_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Listener" ], "type": "alias" }
      ],
      [
       { "params": [ "management_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Management" ], "type": "alias" }
      ],
      [
       { "params": [ "rollup_indexing_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "RollUPIndexing" ], "type": "alias" }
      ],
      [
       { "params": [ "search_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Search" ], "type": "alias" }
      ],
      [
       { "params": [ "write_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_os",
     "query": "// SELECT mean(\"cpu_load_average_1m\") FROM \"$policy\".\"elasticsearch_os\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_os\")\r\n  |> filter(fn: (r) => r._field == \"cpu_load_average_1m\" or  r._field == \"cpu_load_average_5m\" or  r._field == \"cpu_load_average_15m\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "cpu_load_average_1m" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_fs",
     "query": "// SELECT non_negative_derivative(max(\"io_stats_total_operations\"), 1s) FROM \"$policy\".\"elasticsearch_fs\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_fs\")\r\n  |> filter(fn: (r) => r._field == \"io_stats_total_operations\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> derivative(nonNegative: true)",
     "select": [
      [
       { "params": [ "io_stats_total_operations" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Query Cache",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_clusterstats_indices",
     "query": "// SELECT non_negative_derivative(sum(\"query_cache_total_count\"), 1s) FROM \"elasticsearch_clusterstats_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null) offset 1\n// SELECT non_negative_derivative(sum(\"query_cache_hit_count\"), 1s) FROM \"elasticsearch_clusterstats_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null) offset 1\n// SELECT non_negative_derivative(sum(\"query_cache_miss_count\"), 1s) FROM \"elasticsearch_clusterstats_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null) offset 1\n\nfrom(bucket: \"telegraf\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_clusterstats_indices\")\n  |> filter(fn: (r) => r._field == \"query_cache_total_count\" or  r._field == \"query_cache_hit_count\" or  r._field == \"query_cache_miss_count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(nonNegative: true)",
     "select": [
      [
       { "params": [ "query_cache_total_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Old",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "//SELECT non_negative_derivative(sum(\"gc_collectors_old_collection_count\"), 1s) FROM \"elasticsearch_jvm\" WHERE $timeFilter GROUP BY time($__interval) fill(previous) offset 1\n\nfrom(bucket: \"telegraf\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_jvm\")\n  |> filter(fn: (r) => r._field == \"gc_collectors_old_collection_count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(nonNegative: true)",
     "select": [
      [
       {
        "params": [
         "gc_collectors_old_collection_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "alias": "Young",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "// SELECT non_negative_derivative(sum(\"gc_collectors_young_collection_count\"), 1s) FROM \"elasticsearch_jvm\" WHERE $timeFilter GROUP BY time($__interval) fill(previous) offset 1\n\nfrom(bucket: \"telegraf\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_jvm\")\n  |> filter(fn: (r) => r._field == \"gc_collectors_young_collection_count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(nonNegative: true)",
     "select": [
      [
       {
        "params": [
         "gc_collectors_young_collection_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Run Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "//SELECT non_negative_derivative(max(\"gc_collectors_old_collection_time_in_millis\"), 1s) AS \"Old\", non_negative_derivative(max(\"gc_collectors_young_collection_time_in_millis\"), 1s) AS \"Young\" FROM \"$policy\".\"elasticsearch_jvm\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_jvm\")\r\n  |> filter(fn: (r) => r._field == \"gc_collectors_old_collection_time_in_millis\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> derivative(nonNegative: true)",
     "select": [
      [
       {
        "params": [
         "gc_collectors_old_collection_time_in_millis"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Old" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "gc_collectors_young_collection_time_in_millis"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Young" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "//SELECT non_negative_derivative(max(\"gc_collectors_old_collection_time_in_millis\"), 1s) AS \"Old\", non_negative_derivative(max(\"gc_collectors_young_collection_time_in_millis\"), 1s) AS \"Young\" FROM \"$policy\".\"elasticsearch_jvm\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_jvm\")\r\n  |> filter(fn: (r) => r._field == \"gc_collectors_young_collection_time_in_millis\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> derivative(nonNegative: true)",
     "select": [
      [
       {
        "params": [
         "gc_collectors_old_collection_time_in_millis"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Old" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "gc_collectors_young_collection_time_in_millis"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Young" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "// SELECT mean(\"mem_heap_max_in_bytes\") FROM \"$policy\".\"elasticsearch_jvm\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_jvm\")\r\n  |> filter(fn: (r) => r._field == \"mem_heap_max_in_bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "mem_heap_max_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    },
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_jvm",
     "query": "// SELECT mean(\"mem_heap_used_in_bytes\") FROM \"$policy\".\"elasticsearch_jvm\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_jvm\")\r\n  |> filter(fn: (r) => r._field == \"mem_heap_used_in_bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "mem_heap_used_in_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Indexing Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "// SELECT non_negative_derivative(max(\"indexing_index_total\"), 1s) FROM \"$policy\".\"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)\n\nfrom(bucket: \"telegraf\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_indices\")\n  |> filter(fn: (r) => r._field == \"indexing_index_total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> derivative(nonNegative: true)",
     "select": [
      [
       { "params": [ "indexing_index_total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Search Fetch Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "// SELECT non_negative_derivative(max(\"search_fetch_time_in_millis\"), 1s) FROM \"$policy\".\"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(previous)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_indices\")\r\n  |> filter(fn: (r) => r._field == \"search_fetch_time_in_millis\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> derivative(nonNegative: true)",
     "select": [
      [
       { "params": [ "search_fetch_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Get Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "// SELECT non_negative_derivative(max(\"get_time_in_millis\"), $__interval) FROM \"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null) offset 1\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_indices\")\r\n  |> filter(fn: (r) => r._field == \"get_time_in_millis\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> derivative(nonNegative: true)",
     "select": [
      [
       { "params": [ "get_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Search Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "// SELECT non_negative_derivative(max(\"search_query_total\"), 1s) FROM \"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null) offset 1\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_indices\")\r\n  |> filter(fn: (r) => r._field == \"search_query_total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> derivative(nonNegative: true)",
     "select": [
      [
       { "params": [ "search_query_total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Index Max Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "// SELECT non_negative_derivative(max(\"indexing_index_time_in_millis\"), 1s) FROM \"$policy\".\"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_indices\")\r\n|> filter(fn: (r) => r._field == \"indexing_index_time_in_millis\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n|> derivative()",
     "select": [
      [
       { "params": [ "indexing_index_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Merges Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "// SELECT non_negative_derivative(max(\"merges_total_time_in_millis\"), 1s) FROM \"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null) offset 1\n\nfrom(bucket: \"telegraf\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_indices\")\n  |> filter(fn: (r) => r._field == \"merges_total_time_in_millis\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> derivative(nonNegative: true)",
     "select": [
      [
       { "params": [ "merges_total_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Merges Current",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "// SELECT max(\"merges_current\") FROM \"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null) offset 1\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_indices\")\r\n  |> filter(fn: (r) => r._field == \"merges_current\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)",
     "select": [
      [
       { "params": [ "merges_current" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Flush Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "// SELECT non_negative_derivative(max(\"flush_total_time_in_millis\"), $__interval) FROM \"$policy\".\"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_indices\")\r\n  |> filter(fn: (r) => r._field == \"flush_total_time_in_millis\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> derivative(nonNegative: true)",
     "select": [
      [
       { "params": [ "flush_total_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Search Query Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "elasticsearch_indices",
     "query": "// SELECT non_negative_derivative(max(\"search_query_time_in_millis\"), 1s) FROM \"$policy\".\"elasticsearch_indices\" WHERE (\"cluster_name\" =~ /^$cluster$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(previous)\r\n\r\nfrom(bucket: \"telegraf\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"elasticsearch_indices\")\r\n  |> filter(fn: (r) => r._field == \"search_query_time_in_millis\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> derivative(nonNegative: true)",
     "select": [
      [
       { "params": [ "search_query_time_in_millis" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "cluster_name", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  }
 ]
}