{
 "title": "Nginx",
 "description": "Grafana Dashboard for Nginx Web Server.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "hostname",
    "label": "instance",
    "query": {
     "query": "label_values(nginx_requests, host)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(nginx_requests{host=\"$hostname\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Nginx Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nginx Connections / $inter",
   "type": "timeseries",
   "description": "The total number of accepted connections from clients since the nginx master process started. Note that reloading configurations or restarting worker processes will not reset this metric. If you terminate and restart the master process, you will reset the metric.\n\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (host) (rate(nginx_accepts{container=~\"$container\",host=~\"$hostname*\"}[$inter]))",
     "legendFormat": "Accepts"
    },
    {
     "expr": "sum by (host) (rate(nginx_active{container=~\"$container\",host=~\"$hostname*\"}[$inter]))",
     "legendFormat": "Active"
    },
    {
     "expr": "sum by (host) (rate(nginx_handled{container=~\"$container\",host=~\"$hostname*\"}[$inter]))",
     "legendFormat": "Handled"
    },
    {
     "expr": "sum by (host) (rate(nginx_requests{container=~\"$container\",host=~\"$hostname*\"}[$inter]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Nginx Connections",
   "type": "timeseries",
   "description": "The current number of active (accepted) connections from clients. Includes all connections with the statuses Idle / Waiting, Reading, and Writing.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (hostname) (nginx_waiting{container=~\"$container\",host=~\"$hostname\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum by (hostname) (nginx_writing{container=~\"$container\",host=~\"$hostname\"})",
     "legendFormat": "Writing"
    },
    {
     "expr": "sum by (hostname) (nginx_reading{container=~\"$container\",host=~\"$hostname\"})",
     "legendFormat": "Reading"
    }
   ]
  },
  {
   "title": "Nginx Connection Rate / [$inter]",
   "type": "timeseries",
   "description": "The current rate of active (accepted) connections from clients. Includes all connections with the statuses Idle / Waiting, Reading, and Writing.\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(nginx_waiting{container=~\"$container\",host=~\"$hostname*\"}[$inter]))",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum by (hostname) (rate(nginx_writing{container=~\"$container\",host=~\"$hostname*\"}[$inter]))",
     "legendFormat": "Writing"
    },
    {
     "expr": "sum by (hostname) (rate(nginx_reading{container=~\"$container\",host=~\"$hostname*\"}[$inter]))",
     "legendFormat": "Reading"
    }
   ]
  }
 ]
}