---
apache_info_regexp: '^(?<client>[^, ]*)(, (?<chain1>[^, ]+))?(, (?<chain2>[^ ]+))? (?<host>[^ ]*) (?<user>[^ ]*) \[(?<localtime>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +(?<protocol>\S*))?" (?<status>[^ ]*) (?<size>[^ ]*)(?:\s+"(?<referrer>[^\"]*)" "(?<agent>[^\"]*)" (?<error_id>[^ ]+) (?<duration>[^ ]+) (?<request_id>[^ ]+))?( (?<connection_id>[^ ]+))?( (?<qos_ev>[^ ]+))?( (?<qos_cr>[^ ]+))?( (?<qos_com>[^ ]+))?'

services:
  - "{{ elasticsearch_container }}"
  - "{{ kibana_container }}"

fluentd:
  image: "{{ registry.common }}/fluentd"
  version: "v1.16.2-1.0"
  directory: "{{ docker.directory }}/{{ fluentd_container.name }}"
  ports:
    - "{{ fluentd_container.port.metrics }}:{{ fluentd_container.port.metrics }}"
    - "{{ fluentd_container.port.logging }}:{{ fluentd_container.port.logging }}"
    - "{{ fluentd_container.port.logging }}:{{ fluentd_container.port.logging }}/udp"
    - "{{ fluentd_container.port.syslog }}:{{ fluentd_container.port.syslog }}"
    - "{{ fluentd_container.port.syslog }}:{{ fluentd_container.port.syslog }}/udp"
  buffer: "/var/log/fluentd-buffers"
  custom: "{{ lookup('template', 'fluentd-custom.yml.j2') }}"
  logging:
    driver: "json-file"
    options: 
      max-size: "10m"
      max-file: "3"

elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch"
  version: "8.6.2"
  directory: "{{ docker.directory }}/{{ elasticsearch_container.name }}"

es_exporter:
  image: "quay.io/prometheuscommunity/elasticsearch-exporter"
  version: "v1.5.0"

kibana:
  image: "docker.elastic.co/kibana/kibana"
  version: "8.6.2"
  xpack_reporting_encryptionKey: "{{ vault_kibana.xpack_reporting_encryptionKey }}"
