---
- name: "Logging DNS"
  tags:
    - dns
  include_role:
    name: dns


- name: "Elasticserach"
  include_tasks: "elasticsearch.yml"

- name: "Fluentd"
  include_tasks: "fluentd.yml"

- name: "Kibana"
  include_tasks: "kibana.yml"


- name: "Services"
  include_tasks: "services.yml"
