---
- name: "Sensu container restart"
  tags:
    - container
    - sensu
  docker_container:
    name: sensu
    state: absent


- name: "Restart logrotate"
  systemd:
    name:  "logrotate"
    state: "restarted"
