---
env: "infra"

az:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c

ec2_images: 
# eu-west-1:    "ami-02d1083d1af7ad6e7" # Private CentOS
# eu-west-1:    "ami-004c2c678f905016f" # CentOS
# eu-west-1:    "ami-0ec23856b3bad62d3" # RHEL
  eu-west-1:    "ami-063d4ab14480ac177" # Amazon Linux 2
# eu-west-1:    "ami-035966e8adab4aaad" # ubuntu
  eu-central-1: "ami-07cda0db070313c52"
  us-east-1:    "ami-0d50d8864c5cdd573"
  us-west-1:    "ami-03caa3f860895f82e"
  us-west-2:    "ami-003d8924a33dc0fd7"

ec2_default_image: "{{ ec2_images[region] }}"

ec2_state: "running"
elastic_ip_groups: []
email: "{{ instance }}-ops-alerts@epimorphics.com" # Note {{ domain }} is .net

hostname_root: "{{ instance }}-{{ env }}" # basis for the hostname
hostname_index: true                      # are hosts numbered (even if there is only 1)

iam_role: "{{ instance }}-ec2"

iam_policies:
 - "arn:aws:iam::{{ aws.account }}:policy/{{ sns.policy.name }}"
 - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"

key:
  name: "{{ instance }}"
  material: "{{ lookup('file', 'id_rsa.pub') }}"

security_group: "default"

s3_readwrite:
  - "{{ s3_bucket }}"
  - "{{ s3_logs }}"

# staff: "{{ vault_staff }}"

ssl_certificate_id: "arn:aws:acm:eu-west-1:{{ aws.account }}:certificate/aa40074e-6439-4158-b7c0-9fa8a5002718"

vpc:
  name: "{{ instance }}-vpc"
  cidr: "{{ internal_subnet }}"

lambda:
  name: "sns2slack"
  description: "SNS to Slack Webhook"
  s3_bucket: "epi-repository"
  runtime: "python3.8"
  version: "v2.06"

elb:
  timeout:  120 # seconds

sns:
  policy:
    name: "{{ instance }}-alert-publisher"
    description: "SNS Alert Publication"
  topic:
    name:
      email: "{{ sns_email }}"
      slack: "{{ sns_slack }}"
    display_name:
      email: "{{ notification }} - Email"
      slack: "{{ notification }} - Slack"
    delivery_policy:
      http:
        defaultHealthyRetryPolicy:
          minDelayTarget: 2
          maxDelayTarget: 4
          numRetries: 3
          numMinDelayRetries: 0
          numMaxDelayRetries: 3
          numNoDelayRetries: 0
          backoffFunction: "linear"
        disableSubscriptionOverrides: True
        defaultThrottlePolicy:
          maxReceivesPerSecond: 10
