---
- name: "Restart docker"
  systemd:
    name:  "{{ docker.service.name | default('docker') }}"
    state: restarted
    daemon_reload: yes

- name: "Restart telegraf"
  systemd:
    name:  "telegraf"
    state: restarted
