---
services:
  - "{{ alertmanager_container }}"


alertmanager:
  image: "prom/alertmanager"
  version: "v0.27.0"
  directory: "{{ docker.directory }}/{{ alertmanager_container.name }}"
  config: "alertmanager.yml"
  template: "slack.tmpl"


alertmanager_routes:
  default: default
  receivers:
  - name: default
    email: "{{ email }}"
    slack: "{{ slack }}"


sns_forwarder:
  image: "datareply/alertmanager-sns-forwarder"
  version: "0.2"
