---
services:
  - "{{ alertmanager_container }}"


alertmanager:
  image: "prom/alertmanager"
  version: "v0.27.0"
  directory: "{{ docker.directory }}/{{ alertmanager_container.name }}"
  config: /etc/alertmanager/alertmanager.yml


sns_forwarder:
  image: "datareply/alertmanager-sns-forwarder"
  version: "0.2"
