{
 "title": "Fuseki",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(fuseki_requests,application)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(fuseki_requests{application=\"$application\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$instance\",application=\"$application\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\",application=\"$application\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\",application=\"$application\",area=\"heap\"})*100/sum(jvm_memory_max_bytes{instance=\"$instance\",application=\"$application\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\",application=\"$application\",area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{instance=\"$instance\",application=\"$application\",area=\"nonheap\"})"
    }
   ]
  },
  { "title": "Fuseki", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Fuseki Requests Good",
   "type": "graph",
   "description": "fuseki_requests_good",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(fuseki_requests_good{instance=\"$instance\",application=\"$application\"}[1m])",
     "legendFormat": "{{description}}/{{endpoint}}"
    }
   ]
  },
  {
   "title": "Fuseki Requests Bad",
   "type": "graph",
   "description": "fuseki_requests_bad",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(fuseki_requests_bad{instance=\"$instance\",application=\"$application\"}[1m])",
     "legendFormat": "{{description}}/{{endpoint}}"
    }
   ]
  },
  { "title": "Threads/Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Classes",
   "type": "graph",
   "description": "jvm_classes_loaded_classes\njvm_classes_unloaded_classes",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{instance=\"$instance\",application=\"$application\"}",
     "legendFormat": "Loaded"
    },
    {
     "expr": "jvm_classes_unloaded_classes{instance=\"$instance\",application=\"$application\"}",
     "legendFormat": "Unloaded"
    }
   ]
  },
  {
   "title": "Buffer count",
   "type": "graph",
   "description": "jvm_buffer_count_buffers",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{instance=\"$instance\",application=\"$application\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Buffer total capacity",
   "type": "graph",
   "description": "jvm_buffer_total_capacity_bytes",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\",application=\"$application\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "description": "jvm_threads_daemon_threads",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\",application=\"$application\"}",
     "legendFormat": "Daemon Threads"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\",application=\"$application\"}",
     "legendFormat": "Live Threads"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\",application=\"$application\"}",
     "legendFormat": "Peak Threads"
    }
   ]
  },
  {
   "title": "Memory Committed",
   "type": "graph",
   "description": "jvm_memory_committed_bytes",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\",application=\"$application\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Buffer Memory Used",
   "type": "graph",
   "description": "jvm_buffer_memory_used_bytes",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\",application=\"$application\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "jvm_memory_used_bytes",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\",application=\"$application\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Threads States",
   "type": "graph",
   "description": "jvm_threads_state_threads",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{instance=\"$instance\",application=\"$application\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "GC Live Data",
   "type": "graph",
   "description": "jvm_gc_live_data_size_bytes",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_live_data_size_bytes{instance=\"$instance\",application=\"$application\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_gc_max_data_size_bytes{instance=\"$instance\",application=\"$application\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Pause Max(s)",
   "type": "graph",
   "description": "jvm_gc_pause_seconds_max",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_max{instance=\"$instance\",application=\"$application\"}[5m])",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "GC Memory",
   "type": "graph",
   "description": "jvm_gc_memory_allocated_bytes_total\njvm_gc_memory_promoted_bytes_total",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\",application=\"$application\"}[5m])",
     "legendFormat": "Allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\",application=\"$application\"}[5m])",
     "legendFormat": "Promoted"
    }
   ]
  },
  {
   "title": "GC Pause(s)",
   "type": "graph",
   "description": "jvm_gc_pause_seconds_count",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{instance=\"$instance\",application=\"$application\"}[5m])",
     "legendFormat": "{{cause}}"
    }
   ]
  }
 ]
}