{
 "title": "Ruby Application",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=\"$application\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Application Errors",
   "type": "stat",
   "description": "rate(internal_application_error)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(internal_application_error{job=\"$application\"}[1m]) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Connection Failures",
   "type": "stat",
   "description": "rate(api_connection_failure)",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_connection_failure{job=\"$application\"}[1m]) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Service Exceptions",
   "type": "stat",
   "description": "rate(api_service_exception)",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_service_exception{job=\"$application\"}[1m]) or on() vector(0))"
    }
   ]
  },
  {
   "title": "API Request Failures",
   "type": "stat",
   "description": "rate(api_requests{result!=\"success\"})",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_requests{result!=\"success\",job=\"$application\",}[1m]) or on() vector(0))"
    }
   ]
  },
  {
   "title": "API Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "2.. [RPM]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_status{job=\"$application\",status=~\"2..\"}[1m]) or on() vector(0))"
    }
   ]
  },
  {
   "title": "3.. [RPM]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_status{job=\"$application\",status=~\"3..\"}[1m]) or on() vector(0))"
    }
   ]
  },
  {
   "title": "4.. [RPM]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_status{job=\"$application\",status=~\"4..\"}[1m]) or on() vector(0))"
    }
   ]
  },
  {
   "title": "5.. [RPM]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_status{job=\"$application\",status=~\"5..\"}[1m]) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used ",
   "type": "graph",
   "description": "memory_used_mb",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "memory_used_mb{job=\"$application\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Count by Instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"$application\"}[1m] )) by (instance) > 0.00001",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection failures [RPM]",
   "type": "graph",
   "description": "rate(api_connection_failure)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_connection_failure{job=\"$application\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Count by URI",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"$application\"}[1m] )) by (path,method) > 0.00001",
     "legendFormat": "{{method}}: {{path}}"
    }
   ]
  },
  {
   "title": "API Requests [RPM]",
   "type": "graph",
   "description": "rate(api_requests)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(api_requests{job=\"$application\"}[1m])",
     "legendFormat": "{{instance}}:{{result}}"
    }
   ]
  },
  {
   "title": "Average Request time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (method,path) (rate(http_server_request_duration_seconds_sum{job=\"$application\"}[1m])/rate(http_server_request_duration_seconds_count{job=\"$application\"}[1m])) > 0",
     "legendFormat": "{{method}}: {{path}}"
    }
   ]
  },
  {
   "title": "Performance Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Http Request Duration Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_server_request_duration_seconds_bucket{job=\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Http Request Duration Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=\"$application\"}[$__interval]) > 0.0000000001) by (le)  ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "API Response Duration Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(api_response_times_bucket{job=\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "API Response Duration Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(api_response_times_bucket{job=\"$application\"}[$__interval]) > 0.0000000001) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}