---
- name: "Iptable-nft"
  tags:
    - pkg
  package:
    name: iptables-nft
    state: latest


- name: "AWS ECR Helper Archive"
  tags:
    - pkg
  unarchive:
    src: "https://epi-repository.s3.eu-west-1.amazonaws.com/release/RHEL/{{ ansible_distribution_major_version }}/amazon-ecr-credential-helper/docker-credential-ecr-login.zip"
    dest: /bin
    remote_src: yes 
  loop_control: 
    label: "AWS ECR Helper"


- name: "AWS ECR Helper permissions"
  tags:
    - pkg
  file:
    path: /bin/docker-credential-ecr-login
    owner: root 
    group: root 
    mode: 0755
