---
- name: "Install {{ docker_package[ansible_distribution] }}"
  tags:
    - pkg
  package:
    name: "{{ docker_package[ansible_distribution] }}"
    state: latest


- name: "Install python-docker"
  tags:
    - pkg
    - pip
  pip:
    executable: pip3
    name: docker
    state: latest
  when: not ansible_check_mode


- name: "AWS ECR helper"
  tags:
    - pkg
  yum:
    name: amazon-ecr-credential-helper
    state: latest
