---
- name: "Docker CE repository"
  yum_repository:
    name: docker
    description: Docker CE
    file: docker
    baseurl: "https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/$basearch/stable"
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
  when: docker.package.name == "docker-ce"


- name: "Install docker"
  tags:
    - pkg
  package:
    name: "docker-ce"
    state: latest
  notify: "Restart docker"


- name: "Install python-docker"
  tags:
    - pkg
    - pip
  pip:
    executable: pip3
    name: docker
    state: latest
  when: not ansible_check_mode


- name: "AWS ECR Helper Archive"
  tags:
    - pkg
  unarchive:
    src: "https://epi-repository.s3.eu-west-1.amazonaws.com/release/RHEL/{{ ansible_distribution_major_version }}/amazon-ecr-credential-helper/docker-credential-ecr-login.zip"
    dest: /bin
    remote_src: yes 
  loop_control: 
    label: "AWS ECR Helper"


- name: "AWS ECR Helper permissions"
  tags:
    - pkg
  file:
    path: /bin/docker-credential-ecr-login
    owner: root 
    group: root 
    mode: 0755
