- name: "Install {{ docker_package[ansible_distribution] }}"
  tags:
    - pkg
  package:
    name: "{{ docker_package[ansible_distribution] }}"
    state: latest
  notify: "Restart docker"


- name: "AWS ECR Helper Archive"
  tags:
    - pkg
  unarchive:
    src: "{{ s3_release }}/{{ ansible_distribution }}/{{ ansible_distribution_major_version }}/amazon-ecr-credential-helper/docker-credential-ecr-login-0.9.1.tgz"
    dest: /bin
    remote_src: yes 
  loop_control: 
    label: "AWS ECR Helper"


- name: "AWS ECR Helper permissions"
  tags:
    - pkg
  file:
    path: /bin/docker-credential-ecr-login
    owner: root 
    group: root 
    mode: 0755


- name: "Install python-docker"
  tags:
    - pkg
  package:
    name: python3-docker
    state: latest
  when: not ansible_check_mode
