---
- name: "CName records ( {{ route53_profile }} )"
  become: no
  delegate_to: localhost
  tags:
    - dns
  route53:
    state: present
    hosted_zone_id: "{{ hosted_zone_id }}"
    profile: "{{ route53_profile }}"
    record: "{{ item.cname | default(item.name) }}-{{ instance }}.{{ domain }}"
    type: CNAME
    value: "{{ hostname }}.{{ domain }}"
    overwrite: yes
  loop_control:
    label: "{{ item.cname | default(item.name) }}-{{ instance }}.{{ domain }} -> {{ hostname }}.{{ domain }}"
  loop: "{{ services }}"
