- name: "EPEL Repository"
  yum_repository:
    name: "epel"
    description: "EPEL YUM repo"
    file: "epel"
    baseurl: "https://download.fedoraproject.org/pub/epel/$releasever/Everything/$basearch/"
    gpgcheck: "yes"
    gpgkey: "https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"


- name: "Yum Utils package"
  tags:
    - pkg
  package:
    name:
      - yum-utils
    state: latest


- name: "Text Selection bracketing"
  lineinfile:
    path: "/etc/inputrc"
    regexp: "enable-bracketed-paste"
    line: "set enable-bracketed-paste off"


- name: "Disable swappiness"
  lineinfile:
    line: vm.swappiness = 0
    regexp: ^vm.swappiness
    path: /etc/sysctl.d/90-swappiness
    create: true
