---
- name: "Disks"
  include_tasks: "disks.yml"

- name: "{{ ansible_distribution }}"
  include_tasks: "{{ ansible_distribution }}.yml"


- name: "Hostname"
  tags:
    - cfg
    - hostname
  hostname:
    name: "{{ hostname }}.{{ domainname }}"


- name: "NTP"
  include_tasks: "ntp.yml"


- name: "Secure system files"
  tags:
    - cfg
  copy:
    src: "{{ item | basename }}"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "/etc/at.allow"
    - "/etc/cron.allow"
    - "/etc/security/limits.conf"
    - "/etc/ssh/sshd_banner"


- name: "SSH daemon config"
  tags:
    - cfg
  lineinfile:
    path: "/etc/ssh/sshd_config"
    line: "Banner /etc/ssh/sshd_banner"
    regexp: "#?Banner\\s"
    owner: root
    group: root
    mode:  0644
  notify: "Restart sshd"


- name: "Forward syslog"
  tags:
    - cfg
    - logging
    - syslog
  template:
    src: "fluentd.conf.j2"
    dest: "/etc/rsyslog.d/99-fluentd.conf"
    owner: root
    group: root
    mode: 0644
  notify: "Restart rsyslog"
  when:
    -  groups['monitor'] is defined
    -  hostvars[groups['monitor'][0]].ansible_default_ipv4 is defined
    -  logging is defined


- name: "Log rotation"
  tags:
    - cfg
    - logging
    - syslog
  template:
    dest: "/etc/logrotate.conf"
    src: "logrotate.conf.j2"
    owner: root
    group: root
  when: logrotate is defined
  notify: "Restart logrotate"


- name: "Journald volatile"
  tags:
    - cfg
  lineinfile:
    path: "/etc/systemd/journald.conf"
    line: "Storage=volatile"
    regexp: "#?Storage="
    owner: root
    group: root
    mode:  0644
  notify: "Restart journald"


- name: "Utility packages"
  tags:
    - pkg
  package:
    name: 
      - jq
      - pv
      - rsync
      - unzip
    state: latest


- name: "Package update"
  include_tasks: "update.yml"


- name: "Services"
  include_tasks: "services.yml"
