---
- meta: flush_handlers


- name: "Journald service"
  tags:
    - services
  service:
    name:  "systemd-journald"
    state: started
    enabled: yes


- name: "NTP service ({{ ntp.service }})"
  tags:
    - services
  service:
    name:  "{{ ntp.service }}"
    state: started
    enabled: yes


- name: "SSH service"
  tags:
    - services
  service:
    name:  "{{ (ansible_distribution == 'Ubuntu') | ternary('ssh', 'sshd') }}"
    state: started
    enabled: yes
