parse:
  directory: "/var/log/docker/proxy/goaccess"
  dest: "/var/lib/docker/proxy/www/logs"
  file: "/usr/local/bin/proxy-parse.sh"
  src: "s3://{{ s3_logs }}/logs"
  types: "{{ external_proxy_host_types }}"
  wrapper:
    daily: "/root/yesterday-proxy-log.sh"
    today: "/root/today-proxy-log.sh"

