---
services:
  - "{{ grafana_container }}"
  - "{{ influxdb_container }}"
  - "{{ prometheus_container }}"

grafana:
  image: "grafana/grafana-enterprise"
# version: "9.2.5"
  version: "11.1.5"
  directory: "{{ docker.directory }}/{{ grafana_container.name }}"

influxdb:
  image: "influxdb"
  version: "2.7.5"
  directory: "{{ docker.directory }}/{{ influxdb_container.name }}"
  config: "/etc/influxdb2"
  data: "/var/lib/influxdb2"

prometheus:
  image: "docker.io/prom/prometheus"
  version: "v2.54.1"
  directory: "{{ docker.directory }}/{{ prometheus_container.name }}"

prometheus_rules:
  - "disk"
  - "logging"
  - "targets"

prom_rules:
  absolute:
    disk:
      warning:  90
      critical: 95
    inode:
      warning:  90
      critical: 95
  projected:
    warning: 14d
    critical: 24h

repository: "{{ instance }}-ansible-deployment"
