---
- name: "Influxdb volume"
  tags:
    - cfg
    - influxdb
  file:
    path: "{{ influxdb.directory }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  notify: "Influxdb container restart"


- name: "Influxdb config"
  tags:
    - cfg
    - influxdb
  template:
    src: "influxdb.conf.j2"
    dest:  "{{ docker.directory }}/influxdb.conf"
    owner: root
    group: root
    mode: "0644"
  notify: "Influxdb container restart"


- meta: flush_handlers


- name: "Influxdb container"
  tags:
    - container
    - influxdb
  docker_container:
    name: "{{ influxdb_container.name }}"
    image: "{{ influxdb.image }}:{{ influxdb.version }}"
    env:
      INFLUXDB_ADMIN_USER: "{{ influxdb.user.admin }}"
      INFLUXDB_ADMIN_PASSWORD: "{{ password.influxdb.admin }}"
    log_driver: "{{ docker.logging.driver }}"
    log_options: "{{ docker.logging.options }}"
    network_mode: "{{ docker.network.mode }}"
    networks:
      - name: "{{ docker.network.name }}"
    restart_policy: "unless-stopped"
    networks_cli_compatible: yes
    ports:
      - "{{ influxdb_container.port.http }}:{{ influxdb_container.port.http }}"
    volumes:
      - "{{ docker.directory }}/influxdb.conf:/etc/influxdb/influxdb.conf"
      - "{{ influxdb.directory }}:{{ influxdb.store }}"
