---
- name: "Metrics DNS"
  tags:
    - dns
  include_role:
    name: dns


- name: "InfluxDB"
  include_tasks: "influxdb.yml"

- name: "Prometheus"
  include_tasks: "prometheus.yml"

- name: "Grafana"
  include_tasks: "grafana.yml"
