---
- name: "Discover monitor facts"
  setup:
  delegate_to: '{{item}}'
  delegate_facts: yes
  when: hostvars[item]["ansible_all_ipv4_addresses"] is not defined
  with_items: '{{groups["monitor"]}}'


- name: "Telegraf config directory"
  tags:
    - cfg
    - telegraf
  file:
    state: "directory"
    path : "{{ item }}"
    owner: root
    group: root
    mode: "0755"
  loop: 
    - /etc/telegraf
    - /etc/telegraf/telegraf.d


- name: "Telegraf repository"
  yum_repository:
    name: influxdb
    description: InfluxData Repository - Stable
    file: influxdb
    baseurl: "https://repos.influxdata.com/stable/$basearch/main"
    gpgkey: "https://repos.influxdata.com/influxdata-archive_compat.key"
    gpgcheck: yes


- name: "Install telegraf"
  tags:
    - pkg
  package:
    name: "telegraf"
    state: "latest"
  notify: "Telegraf service restart"


- name: "Telegraf configuration"
  tags:
    - cfg
    - telegraf
  template:
    dest: "/etc/telegraf/telegraf.conf"
    src: "telegraf.conf.j2"
  notify: "Telegraf service restart"
  

- name: "Services"
  include_tasks: "services.yml"
