---
- name: "Discover monitor facts"
  setup:
  delegate_to: '{{item}}'
  delegate_facts: yes
  when: hostvars[item]["ansible_all_ipv4_addresses"] is not defined
  with_items: '{{groups["monitor"]}}'


- name: "Telegraf config directory"
  tags:
    - cfg
    - telegraf
  file:
    state: "directory"
    path : "{{ item }}"
    owner: root
    group: root
    mode: "0755"
  loop: 
    - /etc/telegraf
    - /etc/telegraf/telegraf.d


- name: "Install telegraf"
  tags:
    - pkg
  yum:
    name:  https://dl.influxdata.com/telegraf/releases/telegraf-1.15.3-1.x86_64.rpm
    state: latest
  notify: "Telegraf service restart"


- name: "Telegraf configuration"
  tags:
    - cfg
  template:
    dest: "/etc/telegraf/telegraf.conf"
    src: "telegraf.conf.j2"
  notify: "Telegraf service restart"
  

- name: "Services"
  include_tasks: "services.yml"
