name: Ansible Galaxy
on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "Build: Ansible Galaxy"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: "Build Changelog"
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{steps.github_release.outputs.changelog}}
        draft: false
        prerelease: false
    - name: "Git Information"
        id: gitinfo
        run: |
          echo ::set-output name=name::${GITHUB_REF#refs/*/}
          echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
    - name: "Install Ansible"
      shell: "bash"
      run: "sudo apt-get install -y ansible"
    - name: "Build Artifact"
      env:
        RELEASE: "${{ github.ref }}"
      shell: "bash"
      run: "cd epimorphics/deployment && make && ls -l"
    - name: "Upload Artifact"
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: epimorphics/deployment/epimorphics-deployment-${{ steps.gitinfo.outputs.tag }}.tar.gz
        asset_name: epimorphics-deployment-${{ steps.gitinfo.outputs.tag }}.tar.gz
        asset_content_type: application/gzip
