name: Ansible Galaxy
on:
  workflow_dispatch: {}
  push:
    tags:
      - "*"

jobs:
  build:
    name: "Build: Ansible Galaxy"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: "Build Changelog"
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "Git Information"
      id: gitinfo
      run: |
        echo name=${GITHUB_REF#refs/*/}       >> $GITHUB_OUTPUT
        echo branch=${GITHUB_REF#refs/heads/} >> $GITHUB_OUTPUT
        echo tag=${GITHUB_REF#refs/tags/}     >> $GITHUB_OUTPUT

    - name: "Install Ansible"
      shell: "bash"
      run: "sudo apt-get install -y ansible"

    - name: "Build Artifact"
      env:
        VERSION: ${{ steps.gitinfo.outputs.tag }}
      shell: "bash"
      run: "make && ls -l"

    - name: Create Release
      id: release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ steps.gitinfo.outputs.tag }}
        body: ${{steps.github_release.outputs.changelog}}
        draft: false
        prerelease: false
        files: |
          epimorphics-deployment-${{ steps.gitinfo.outputs.tag }}.tar.gz
