name: Ansible Galaxy
on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "Build: Ansible Galaxy"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
    - name: "Install Ansible"
      shell: "bash"
      run: "sudo apt-get install -y ansible"
    - name: "Build Artifact"
      env:
        RELEASE: "${{ github.ref }}"
      shell: "bash"
      run: "make && ls -l"
    - name: "Upload Artifact"
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_uri: ${{ steps.release.outputs.upload_url }}
        asset_path: ./epimorphics-deployment-${{ steps.gittag.outputs.tag }}.tar.gz
        asset_name: epimorphics-deployment-${{ github.ref }}.tar.gz
        asset_content_type: application/gzip
